# Generated by Django 4.0.4 on 2022-06-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('details', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('details', models.CharField(max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('images', models.FileField(upload_to='photos/products')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.category')),
            ],
        ),
    ]
